name: mad3_submission_2
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  equatable: ^2.0.5
  flutter_spinkit: ^5.2.1
  form_field_validator: ^1.1.0
  get_it: ^7.7.0
  go_router: ^14.2.0
  http: ^1.2.1
  path_provider: ^2.1.3
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
